/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addressbook;

import javax.swing.table.DefaultTableModel;

/**90
 *
 * @author rlaqjqdyd2
 */
public class FindingForm extends javax.swing.JDialog {

    UpdatingForm updatingForm;
    
    private int[] indexes;
    
    public FindingForm(UpdatingForm updatingForm) {
        this.updatingForm=updatingForm;
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IDC_BUTTON_FIND = new javax.swing.JButton();
        IDC_TEXTFIELD_NAME = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IDC_TABLE_PERSONALS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("찾기");

        IDC_BUTTON_FIND.setText("찾기");
        IDC_BUTTON_FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_FINDActionPerformed(evt);
            }
        });

        jLabel1.setText("성명");

        IDC_TABLE_PERSONALS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "번호", "성명", "주소", "전화번호", "이메일주소"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        IDC_TABLE_PERSONALS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IDC_TABLE_PERSONALS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDC_TABLE_PERSONALSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(IDC_TABLE_PERSONALS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDC_TEXTFIELD_NAME)
                        .addGap(18, 18, 18)
                        .addComponent(IDC_BUTTON_FIND, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDC_BUTTON_FIND)
                    .addComponent(IDC_TEXTFIELD_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDC_BUTTON_FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_FINDActionPerformed
      
        int i=0;
        Personal personal;
      
        String name = IDC_TEXTFIELD_NAME.getText();
        this.indexes = this.updatingForm.addressBook.Find(name);
        
        DefaultTableModel model =(DefaultTableModel)IDC_TABLE_PERSONALS.getModel();
        model.setRowCount(0);
        
        i= 0 ;
        while(i< this.indexes.length){
            model.setRowCount(indexes.length);
            
            personal=this.updatingForm.addressBook.GetAt(indexes[i]);
            IDC_TABLE_PERSONALS.setValueAt(i+1, i, 0);
            IDC_TABLE_PERSONALS.setValueAt(personal.getName(), i, 1);
            IDC_TABLE_PERSONALS.setValueAt(personal.getAddress(), i, 2);
            IDC_TABLE_PERSONALS.setValueAt(personal.getTelephoneNumber(), i, 3);
            IDC_TABLE_PERSONALS.setValueAt(personal.getEmailAddress(), i, 4);
            i++;
        }
        
    }//GEN-LAST:event_IDC_BUTTON_FINDActionPerformed

    private void IDC_TABLE_PERSONALSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDC_TABLE_PERSONALSMouseClicked
        int index;
        
        if(evt.getClickCount() == 2){
            index=IDC_TABLE_PERSONALS.getSelectedRow();
            String name = (String) IDC_TABLE_PERSONALS.getValueAt(index, 1);
            String address = (String) IDC_TABLE_PERSONALS.getValueAt(index, 2);
            String telephoneNumber = (String) IDC_TABLE_PERSONALS.getValueAt(index, 3);
            String emailAddress = (String) IDC_TABLE_PERSONALS.getValueAt(index, 4);
            
            this.updatingForm.IDC_TEXTFIELD_NAME.setText(name);
            this.updatingForm.IDC_TEXTFIELD_ADDRESS.setText(address);
            this.updatingForm.IDC_TEXTFIELD_TELEPHONENUMBER.setText(telephoneNumber);
            this.updatingForm.IDC_TEXTFIELD_EMAILADDRESS.setText(emailAddress);
            
            this.updatingForm.IDC_TABLE_PERSONALS.setRowSelectionInterval(this.indexes[index], this.indexes[index]);
       
            dispose();
        }
    }//GEN-LAST:event_IDC_TABLE_PERSONALSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDC_BUTTON_FIND;
    private javax.swing.JTable IDC_TABLE_PERSONALS;
    private javax.swing.JTextField IDC_TEXTFIELD_NAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
